version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: mediahub-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: mediahub
      MYSQL_USER: mediahub
      MYSQL_PASSWORD: Realist1900
      MYSQL_ROOT_PASSWORD: Realist1900

    volumes:
      - /mnt/mediahub-data/db/mysql:/var/lib/mysql

    ports:
      - "127.0.0.1:3306:3306"
